app:
  user:
    name_length: 50
    email: 255
    password: 6
    size_gravatar: 80
  helpers:
    size_gravatar: 80
  controller:
    page: 10
  session:
    one: 1
config:
  one: 1
  development:
    host: "localhost:3000"
    port: "587"
